name: SentinelOne CNS Scan

on:
  # Triggers the workflow when pull_request created on master/main branch
<<<<<<< HEAD
  [pull_request, push]
=======
  pull_request:
    types: [ opened, reopened, synchronize ]
    branches: [ master, main ]
>>>>>>> 8c6673f0afff9655ac380c62ae9066fcd2fc4c94

jobs:
  s1-cns-cli:
    runs-on: ubuntu-latest
    container:
      image: pingsafe/s1cnscli:latest
      options: --entrypoint ""

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
          fetch-depth: 0

      - name: Configure SentinelOne CNS CLI
        run: s1-cns-cli config --api-token $TOKEN --endpoint-url https://cns.na1.sentinelone.net
        env:
         TOKEN: ${{secrets.SENTINELONE_CNS_TOKEN}}

      - name: Configure git config
        run: git config --global --add safe.directory $PWD

      - name: Run Secret Detector
        id: secret-detector
<<<<<<< HEAD
        run:  s1-cns-cli scan secret -d $PWD --all-commits
        #run:  s1-cns-cli scan secret -d $PWD
        #run:  s1-cns-cli scan secret -d $PWD --pull-request origin/$SRC $DEST --publish-result --repo-full-name $REPO_FULL_NAME  --repo-url $REPO_URL/$REPO_FULL_NAME 

=======
        run:  s1-cns-cli scan secret -d $PWD --pull-request origin/$SRC $DEST --publish-result --repo-full-name $REPO_FULL_NAME  --repo-url $REPO_URL/$REPO_FULL_NAME 
>>>>>>> 8c6673f0afff9655ac380c62ae9066fcd2fc4c94
        env:
          DEST: ${{ github.event.pull_request.base.sha }}
          SRC: ${{ github.event.pull_request.head.ref }}
          REPO_FULL_NAME: ${{ github.repository }}
          REPO_URL: ${{ github.server_url }}
      
      - name: Run IaC Scanner
        run:  s1-cns-cli scan iac -d $PWD --publish-result --repo-full-name $REPO_FULL_NAME  --repo-url $REPO_URL/$REPO_FULL_NAME --branch $BRANCH
<<<<<<< HEAD
        #run:  s1-cns-cli scan iac -d $PWD --publish-result --repo-full-name $REPO_FULL_NAME  --repo-url $REPO_URL/$REPO_FULL_NAME --branch $BRANCH

        env:
          REPO_FULL_NAME: ${{ github.repository }}
          REPO_URL: ${{ github.server_url }}
          BRANCH: ${{ github.ref_name }}
=======
        env:
          REPO_FULL_NAME: ${{ github.repository }}
          REPO_URL: ${{ github.server_url }}
          BRANCH: ${{ github.event.pull_request.head.ref }}
>>>>>>> 8c6673f0afff9655ac380c62ae9066fcd2fc4c94

      - name: Run Vulnerability Scanner
        run:  s1-cns-cli scan vuln -d $PWD
